### ISSUE TITLE
qemu V7.0 virt changed value of GIC_IRQ_PHANDLE

### ISSUE THREAD

**Issue by tibersam** [seL4/camkes-vm#27]
Hi all,

For the time server our team ported a timer into the qemu v7.0 virt platform. We also do not provide a dtb for the vm during compilation but let the seL4 system modify the system device tree during runtime. When we tried to run the vm_serial_server example, however we did not get any output.

The root of the problem was a wrong value of GIC_IRQ_PHANDLE, in our case it moved from 0x8001 to 0x8002. The Linux kernel did not initialize the virtual pci interface because of the wrong phandle value and therefore hvc0 was also not initialized. In our qemu dtb the phandle was used by the cpu.

I then looked more into how the qemu virt platform assigns  these phandle values. They are incremented for each added phandle. Also the cpu cores are added to the device tree  before the gic and for each cpu core a new phandle is assigned to it. Therefore, depending on the number of available cores, the phandle value will also change. 

I am not sure how to take it from here. Possible solutions to mitigate this problem could be:

- Document this problem in the howto. Something along the lines if a custome qemu is used, look into that qemus dtb and update GIC_IRQ_PHANDLE value accordingly.
- Automatically find the gic in the devicetree during compilation time and set the GIC_IRQ_PHANDLE to the correct value.
- Parse the dtb at runtime to find the correct phandle and use that for the added devices during runtime.

**Comment by chrisguikema** [comment]
@tibersam I just pushed up a PR that deals with this issue. Can you pull it down and check if the PR resolves it? Thanks!

**Comment by axel-h** [comment]
Closing this, because https://github.com/seL4/camkes-vm/pull/52 was merged and we use DTB paths now.
