### ISSUE TITLE
Dont hard-code GIC_IRQ_PHANDLE, read it from device tree instead

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-vm#49]
Follow-up from https://github.com/seL4/camkes-vm/pull/42#discussion_r1005108779

Remove the hard coded `GIC_IRQ_PHANDLE` define and take the value from the device tree instead. Or add at least a sanity check that the hard-coded values machtes the device tree. 

There have been cases, where the `phande` changes, and that causes strange errors then. 
See also https://github.com/seL4/camkes-vm/issues/27

**Comment by chrisguikema** [comment]
Can we define an `INTERRUPT_CONTROLLER` macro instead? That way you can read that node from the device tree, and get the `phandle`?

**Comment by chrisguikema** [comment]
Is that something that is consistent on a per-platform basis?

Here is the boot core node on a zynqmp device tree:
```
		cpu@0 {
			compatible = "arm,cortex-a53";
			device_type = "cpu";
			enable-method = "psci";
			operating-points-v2 = <0x01>;
			reg = <0x00>;
			cpu-idle-states = <0x02>;
			clocks = <0x03 0x0a>;
			phandle = <0x3d>;
		};
```

On a tx2 device tree, I see `<interrupt-parent>` right on top.

**Comment by kent-mcleod** [comment]
I see.  I guess defining the path is good enough. It could also be used to setup the virtual gic without having to hardcode the addresses for each platform.

**Comment by chrisguikema** [comment]
Created a PR for that here: https://github.com/seL4/seL4_projects_libs/pull/83

**Comment by axel-h** [comment]
Closing this, because https://github.com/seL4/camkes-vm/pull/52 was merged and we use DTB paths now.
